### ISSUE TITLE
Silent mode?

### ISSUE THREAD

**Issue by miguelpruivo** [dionmes/node-red-contrib-soma-smartblinds2#1]
Do you have silent mode enable? If so, how to use it? There is a property `morning_mode=1` that can be used as query parameter in order to enable it.

**Comment by dionmes** [comment]
Hi, no this is not implemented. None of the configuration options are implemented, so that should be done via the app. I did a check if this is possible, but there are some dangers with an out of control motor with some wrong bits set. So not eager to implement this.

**Comment by miguelpruivo** [comment]
What do you mean? From what I understood on their API, it should be just setting the `morning_mode=1` query parameter and the motor should run in the silent mode, just as simple as that.

Edit: check [here](https://support.somasmarthome.com/hc/en-us/articles/360026064234-HTTP-API).

**Comment by dionmes** [comment]
That is the API of the SOMA connect. This node does not use Soma Connect, it talks directly via Bluetooth to the Smartblinds. This reduces the need for running Soma Connect.

**Comment by miguelpruivo** [comment]
@dionmes ok, gotcha. I'm trying to search it in the NR dropdown (I use the scan button) but nothing shows up, it's an empty dropdown. What am I suppose to do in order to the device to show here? Is it suppose to show all paired BT devices or just the Soma ones? Because currently it doesn't show up any device, but I've tried running `bluetoothctl list` and the devices are showing up in the console.

<img width="497" alt="Captura de ecrã 2022-09-02, às 16 51 21" src="https://user-images.githubusercontent.com/27860743/188192007-5b7b860a-4094-42e5-9f23-7fc199f864d4.png">

**Comment by dionmes** [comment]
Hm, what device you are running node red on ?

**Comment by miguelpruivo** [comment]
> Hm, what device you are running node red on ?

Raspberry PI 4b

**Comment by dionmes** [comment]
Are you doing sudo when using listing BT devices ?  Check the doc or readme ( https://github.com/dionmes/node-red-contrib-soma-smartblinds2/blob/main/README.md ) to run without SUDO.

**Comment by miguelpruivo** [comment]
Where should I run it and when? Just once on the machine? 

>Are you doing sudo when using listing BT devices ?

Where? With `bluetoothctl list` no I don't. But that's not necessary since it will list the devices anyway.

**Comment by dionmes** [comment]
Yes, just once.

I also think  bluetoothctl list only scans for BT devices, not BLE (low energy). For that you should use 'sudo hcitool lescan' . So did you see an  S or RISE  named device appear ?

Also give the scan some time to fill.

**Comment by miguelpruivo** [comment]
I don't have the SOMA shades yet, but just bought it (I'm waiting to arrive) because I saw there was a NR integration with it — now I'm trying to understand if the setup is ready for it. Are other home BT devices suppose to appear in the dropdown?

Regarding your statement, when I run `bluetoothctl scan on` I can see BLE devices as well (other IoT devices I have at home).

**Comment by dionmes** [comment]
Ah ok, was not sure if it also showed BLE devices. Yes other BLE devices should appear in the dropdown. So if they are not there is something with the BT config, does 'sudo hcitool lescan' work ? This is the BT library that I am using; https://github.com/abandonware/noble

**Comment by miguelpruivo** [comment]
Already ran that command from README and unfortunately there's no devices showing up in the dropdown. I even made sure that I've paired some device with the BT (my iPhone) — not sure if that's a requirement being paired. Anyway, even with that, nothing showed up.

Yes, the `sudo hcitool lescan` works.

Is there any way to check the logs or so?

**Comment by dionmes** [comment]
And hcitool lescan without sudo ? Does that show up devices ? No, they should not be paired. I am running nodered on a Pi 3, this does work.

**Comment by miguelpruivo** [comment]
Yes it does. How can I debug it? Could be something else?

**Comment by dionmes** [comment]
That is indeed weird, it should fill with some devices. I should think of another way of updating the select input, I want it to be realtime. But it is only updated once not pressed, so you press scan, then wait if you can select it, if not you need click somewhere else, to lose focus on the element before it gets updated again. Although I don't think thats your problem. Will also add some more debug messages. See if I can find some time this week.

**Comment by dionmes** [comment]
Oh and I forgot to mention, I do create log messages in the node-red log, see the [soma-smartblinds2:xxxxx] messages.

**Comment by miguelpruivo** [comment]
I’ll check the node red log to see if something catches my eye and I’ll report you back.

**Comment by dionmes** [comment]
You can use the command node-red-log -n 1000 for trailing the last 1000 lines, and keep monitoring.

**Comment by miguelpruivo** [comment]
Hi, I don't have the `node-red-log` command, maybe because I'm using dietpi and installed through `dietpi-software`, however, the NR is the same — just don't have those additional commands.

Edit: Ok, I got the logs. There's nothing relevant there.

**Comment by dionmes** [comment]
Do you see any [soma-smartblinds2:xxxxx] messages ?

**Comment by miguelpruivo** [comment]
No, nothing related with data. But the flow isn't deployed.

**Comment by dionmes** [comment]
Ah, that makes sense but than the node is also not active. So that could the issue. If you can deploy the flow without configuration and then try to scan ? I think nodered does not load the node until deployed, need to find some workaround for that.

**Comment by miguelpruivo** [comment]
That's exactly it. Deployed and it worked immediately @dionmes. Thank you.

**Comment by miguelpruivo** [comment]
Offtopic: how does one use it? Do you have documentation on how to use the commands?

**Comment by dionmes** [comment]
Yes, its in the readme, and also in node-help description. Just like any other node you send it the command like 'moveTo 30' and then it will move the blinds to approximately position 30 (the approximately is a characteristic of the device). The output will report the position and battery status. A couple of other commands are also available.

**Comment by miguelpruivo** [comment]
@dionmes but how do you send the command? What's the format of the payload sent to the node? Do you have an example?

**Comment by dionmes** [comment]
Its just a string. So you can just sent the string with a node like the inject node.  https://nodered.org/docs/tutorials/first-flow
I use a homekit node to sent to command and receive the result, so its integrated with homekit. But you can use all types of nodes.

**Comment by miguelpruivo** [comment]
Ok, I got it working, I'm just experiencing a weird issue: it keeps "connecting" despite finding it without any problem. I could also connect to it but suddenly it stopped working and it keeps saying "connecting". In the app it works.

**Comment by miguelpruivo** [comment]
<img width="327" alt="Captura de ecrã 2022-09-09, às 14 35 27" src="https://user-images.githubusercontent.com/27860743/189362556-daf90970-7b59-4257-b47f-754877c786cd.png">


I'm seeing this a lot of times. Don't know what might be causing it. Is this normal @dionmes ?

**Comment by dionmes** [comment]
This can be dependent on the quality of the BT connection (any walls between the Pi and the device, long distance?). I have them also but not as often so they don't interfere with daily usage. I also cannot control it as it comes from the BT Library.

**Comment by dionmes** [comment]
I actually use an BT USB stick one my Pi and have disabled the internal BT. But that was for other reasons.

**Comment by miguelpruivo** [comment]
@dionmes the devices are closer to each other. I’m using the internal Bluetooth. Any other reason that can be causing it? Do experience any kind of disconnections like these?

**Comment by dionmes** [comment]
No, not like that. Actually since I connected it to the charger (solar) it does not disconnect at all anymore. I did find some disconnect issues for the Pi 4 on Internet, maybe look into that ?

**Comment by miguelpruivo** [comment]
Hum got to take a look! Thank you!
